version: '3'
services:
  postgres:
    image: postgres:12
    container_name: fiber-rest-api-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  redis:
    image: redis:5-alpine
    container_name: fiber-rest-api-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_DB_NUMBER=0
