version: '3'
services:
#  service:
#    image: go-fiber-postgres-builder
#    container_name: go-fiber-service
#    build: ./backend
#    ports:
#      - "8080:8080"
#    volumes:
#      - ${PWD:-./}:/srv
#    working_dir: /srv
#    depends_on:
#      - postgres
#    environment:
#      - DB_USER=postgres
#      - DB_PASSWORD=password
#      - DB_HOST=go-fiber
#      - DB_PORT=5432
#      - DB_DATABASE=gofiber

  postgres:
    image: postgres
    container_name: go-fiber-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gofiber
    # volumes:
    #   - ./databse/migrations/000001_create_init_tables.up.sql:/docker-entrypoint-initdb.d/000001_create_init_tables.up.sql #inisiasi create table berdasarkan file sql