version: '3'
services:
  service:
    container_name: go-fiber-service
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: go-fiber-postgres
    ports:
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST="cgapp-postgres"
      - DB_NAME="postgres"
      - DB_SSL_MODE="disable"

  redis:
    image: redis:5-alpine
    container_name: cgapp-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=cgapp-redis
      - REDIS_DB_NUMBER=0
