version: '3'
services:
  service:
    image: go-fiber:latest
    container_name: fiber-rest-api-service
    working_dir: /build
    build:
      context: .
    volumes:
      - ${PWD:-./}:/build
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    container_name: fiber-rest-api-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ${PWD}/build/dev-postgres/data/:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    container_name: fiber-rest-api-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=fiber-rest-api-redis
      - REDIS_DB_NUMBER=0
