basePath: /
definitions:
  models.SignIn:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 255
        type: string
    required:
    - email
    - password
    type: object
  response.HTTPError:
    properties:
      errorMessage: {}
    type: object
  utils.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: aryanicosa@gmail.com
    name: API Support
  description: This is a sample swagger for Go Fiber Rest API
  title: Fiber Example API
  version: "1.0"
paths:
  /v1/misc/base64encode:
    post:
      consumes:
      - application/json
      description: Encode input string to Base64 string
      parameters:
      - description: arbitrary string
        in: body
        name: StringToEncode
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Encode String to Base64
      tags:
      - Miscellaneous
  /v1/user/sign/in:
    post:
      consumes:
      - application/json
      description: |-
        Sign In a User to get access token
        value of Authorization field is "Basic base64string_of_username:secret"
        use /v1/misc/encode to generate your base64 encoded string
      parameters:
      - description: Basic Auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: User Credentials
        in: body
        name: models.SignIn
        required: true
        schema:
          $ref: '#/definitions/models.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Sign In
      tags:
      - User
swagger: "2.0"
